# Práctica de la librería Numpy

Este es mi notebook relacionado con el ejercicio desarrollado en el curso de Udemy "Python Total".


In [ ]:
# Importamos Numpy con su abreviación "np"
import numpy as np

In [ ]:
# Podemos crear arrays de una dimensión con la función np.array()
array = np.array([1, 2, 3])
print(array)
print()
# O un array de dos dimensiones (bidimensional)
array_2 = np.array([[4, 5, 6, 5],[3, 2, 1, 6]])
print(array_2)
print()
# O un array de tres dimensiones (tridimensional)
array_3 = np.array([[4, 5, 6],[3, 2, 1],[4, 4, 4]])
print(array_3)

[1 2 3]

[[4 5 6 5]
 [3 2 1 6]]

[[4 5 6]
 [3 2 1]
 [4 4 4]]


Para cada uno de estos arrays, podemos obtener sus propiedades, tales como su "forma", número de dimensiones, tipos de datos y tamaño.

In [ ]:
# Atributos del array unidimensional (forma, número de dimensiones, tipos de datos, tamaño, y tipo)
print(array.shape)
print(array.ndim)
print(array.dtype)
print(array.size)
print(type(array))

(3,)
1
int64
3
<class 'numpy.ndarray'>


In [ ]:
# Atributos del array bidimensional
print(array_2.shape)
print(array_2.ndim)
print(array_2.dtype)
print(array_2.size)
print(type(array_2))

(2, 4)
2
int64
8
<class 'numpy.ndarray'>


In [ ]:
# Atributos del array tridimensional
print(array_3.shape)
print(array_3.ndim)
print(array_3.dtype)
print(array_3.size)
print(type(array_3))

(3, 3)
2
int64
9
<class 'numpy.ndarray'>


In [ ]:
# Importamos pandas como pd, y creamos un DataFrame a partir del array bidimensional
import pandas as pd
df = pd.DataFrame(array_2)
print(df)

   0  1  2  3
0  4  5  6  5
1  3  2  1  6


In [ ]:
# Creamos un array de tamaño 5x10, formado únicamente por unos (1)
array_unos = np.ones((5, 10))
print(array_unos)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
# Creamos un array de tamaño 2x4x3, formado únicamente por ceros (0)
array_ceros = np.zeros((2, 3, 4))
print(array_ceros)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
# Creamos un array de números en el rango de 0 a 100, con un paso de 5
array_serie = np.arange(0,101,5)
print(array_serie)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]


In [ ]:
# Creamos un array de números aleatorios enteros comprendidos en entre 0 y 10, de tamaño (2, 5)
array_aleatorio = np.random.randint(0, 11, size=(2, 5))
print(array_aleatorio)

[[ 6  6  5 10  9]
 [ 7  4  9  8 10]]


In [ ]:
# Creamos un array de números aleatorios decimales comprendidos en entre 0 y 1, de tamaño (3, 5)
array_aleatorio_2 = np.random.rand(3, 5)
print(array_aleatorio_2)

[[0.24772054 0.87857072 0.93789796 0.30600962 0.46534981]
 [0.17365457 0.22239385 0.28297816 0.61789544 0.19728761]
 [0.8592404  0.39513751 0.69716513 0.46886743 0.11347052]]


In [ ]:
# Establecemos la "semilla" de números aleatorios en 27
np.random.seed(10000)

# Creamos un array de números aleatorios enteros comprendidos en entre 0 y 10, de tamaño (3, 5)
array_aleatorio_3 = np.random.randint(0, 11, size=(2, 5))
print(array_aleatorio_3)

[[5 8 2 5 8]
 [9 1 6 8 5]]


In [ ]:
# Encontramos los valores únicos del array_2
print(np.unique(array_2))

[1 2 3 4 5 6]


In [ ]:
# Extraemos el elemento de índice 1 del array_2
print(array_2[1])

[3 2 1 6]


In [ ]:
# Extraemos la primera fila del array_2
print(array_2[:1])

[[4 5 6 5]]


In [ ]:
# Extraemos los dos primeros datos de la primera fila del array_2
print(array_2[:1, :2])

[[4 5]]


In [ ]:
# Creamos dos arrays de tamaño 3x4: uno relleno de números aleatorios entre 0 y 10, y otro relleno de unos
array_5 = np.random.randint(0, 11, size=(3, 4))
array_6 = np.ones((3, 4))
print(array_5)
print()
print(array_6)

[[ 9  6  0 10]
 [ 8  6  4  2]
 [ 1  0  5  0]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# Sumamos los dos arrays
print(array_5 + array_6)

[[10.  7.  1. 11.]
 [ 9.  7.  5.  3.]
 [ 2.  1.  6.  1.]]


In [ ]:
# Creamos ahora un array de tamaño (4,3) lleno de unos
array_7 = np.ones((4, 3))

In [ ]:
# Intentaremos sumar los arrays 6 y 7
# print(array_6 + array_7)

In [ ]:
# Entonces crearemos otro array de tamaño (4,3) lleno de unos
array_8 = np.ones((4, 3))

In [ ]:
# Restamos el array_8 al array_7
print(array_7 - array_8)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Creamos otros dos arrays de tamaño 3x3 con números aleatorios del 1 al 5
array_9 = np.random.randint(1, 6, size=(3, 3))
array_10 = np.random.randint(1, 6, size=(3, 3))
print(array_9)
print()
print(array_10)

[[3 2 1]
 [3 4 4]
 [3 2 4]]

[[3 2 3]
 [2 1 4]
 [4 4 2]]


In [ ]:
# Multiplicamos los últimos dos arrays entre sí
print(array_9*array_10)

[[ 9  4  3]
 [ 6  4 16]
 [12  8  8]]


In [ ]:
# Elevamos el array_9 al cuadrado
print(array_9*array_9)

[[ 9  4  1]
 [ 9 16 16]
 [ 9  4 16]]


In [ ]:
# Buscamos la raíz cuadrada del array_10
print(np.sqrt(array_9))

[[1.73205081 1.41421356 1.        ]
 [1.73205081 2.         2.        ]
 [1.73205081 1.41421356 2.        ]]


In [ ]:
# Hallamos el promedio de los valores del array_9
print(np.mean(array_9))

2.888888888888889


In [ ]:
# Hallamos el valor máximo de los valores del array_9
print(np.max(array_9))

4


In [ ]:
# Hallamos el valor mínimo de los valores del array_9
print(np.min(array_9))

In [ ]:
# Cambiamos la forma del array_9 por una de 9x1, y lo almacenamos como array_11
array_11 = array_9.reshape(9, 1)
print(array_11)

[[3]
 [2]
 [1]
 [3]
 [4]
 [4]
 [3]
 [2]
 [4]]


In [ ]:
# Transponemos el array_11
print(np.transpose(array_11))

[[3 2 1 3 4 4 3 2 4]]
[[3 2 1 3 4 4 3 2 4]]


In [ ]:
# Comparamos el array_9 y el array_10, para saber cuáles elementos del array_9 son mayores a los del array_10
array_12 = array_9 > array_10
print(array_12)

[[False False False]
 [ True  True False]
 [False False  True]]


¿Qué tipos de datos forman parte del array de resultados?

In [ ]:
# Veamos sus nuevos tipos de datos
print(array_12.dtype)

bool


In [ ]:
# Alguno de los elementos del array_9 es igual su equivalente del array_10?
print(array_9 > array_10)

[[False False False]
 [ True  True False]
 [False False  True]]


In [ ]:
# Comparamos nuevamente ambos arrays, en esta ocasión con >=
print(array_9 >= array_10)

[[ True  True False]
 [ True  True  True]
 [False False  True]]


In [ ]:
# Buscamos los elementos del array_9 que son mayores a 2
print(array_9 > 2)

In [ ]:
# Ordenamos de menor a mayor los elementos dentro del array_9
print(np.sort(array_9))

[[1 2 3]
 [3 4 4]
 [2 3 4]]
